name: Branch Check

on:
  pull_request:
    branches:
      - master
      - stage
      - dev

jobs:
  branch_check:
    runs-on: ubuntu-latest
    if: github.base_ref == 'master' && github.head_ref != 'stage' || github.base_ref == 'stage' && github.head_ref != 'dev' 
    steps:
      - name: print error and exit process
        run: echo "It's not available branch. (dev->stage->master)" && exit 1
        #  build:
        #    need: branch_check
