name: Branch Check

on:
  pull_request:
    branches:
      - master
      - stage
      - dev

jobs:
  branch_check:
    runs-on: ubuntu-latest
    steps:
      - name: check branches
        if: github.base_ref == 'master' && github.head_ref != 'stage' || github.base_ref == 'stage' && github.head_ref != 'dev' 
        run: echo "It's not available branch. (dev->stage->master)" && exit 1
      - name: success
        if: ${{ success() }}
        run: exit 0
        #  build:
        #    need: branch_check
